### ISSUE TITLE
Component Crashes Browser

### ISSUE THREAD

**Issue by JonesM87** [announcekitapp/announcekit-angular#2]
When passing user and data into the component the component continuously spawns new tabs and crashes the browser.

**To reproduce**
Example here: https://codesandbox.io/s/announcekit-angular-forked-shi67?file=/src/app/app.component.html

Try adding and removing the data bindings, or waiting a few minutes, after a moment you will see many spawned tabs trying to reach https://announcekit.app/widgets/v2/3mYlmU/view

**Comment by JonesM87** [comment]
Is anyone even monitoring these repos...? We will need to look for a better solution I think.

**Comment by namirali** [comment]
Hello Mark, sorry for the late reply, we will take a look and fix this issue in few days, I’ll let you know until Monday

**Comment by namirali** [comment]
Hey @JonesM87 this issue should be solved with 1.0.3, thank you for reporting it
