### ISSUE TITLE
Change color of widget

### ISSUE THREAD

**Issue by anuj-scanova** [announcekitapp/announcekit-angular#6]
using announcekit as
```
<announcekit
                    [widget]="announcekitUrl"
                    [lang]="locale"
                    [widgetStyle]="style">
                    <i class="material-icons">notifications</i>
                    <span i18n>What's New</span>
                  </announcekit>
```
and the `style` variable is
```
style = {
    color: "#ffffff"
  }
```

But it displays black icon.
<img width="252" alt="Screenshot 2022-12-14 at 10 31 20 PM" src="https://user-images.githubusercontent.com/105233146/207659762-6339a2e2-7ee2-4326-ab27-a959966583b2.png">

**Comment by yigitfindikli** [comment]
Hi,

We'll check and get back to you.

**Comment by yigitfindikli** [comment]
You can use widgetStyle for styling the badge icon or you can use the announcekit-widget-badge class. That black icon there are for all read state you can hide it from https://announcekit.app/dashboard/settings/widget. 

![image](https://user-images.githubusercontent.com/19997575/208923520-9a69304a-cd16-48a1-8e09-8e459ebb286f.png)
